# APP PATHS
## 服务端应用包源码所在路径
## src下创建apps和images
### docker、docker-compose、keepalived放到apps下
### 其余docker离线镜像(命名规则:docker-名称-版本号.tar)放到images下
elk_src_dir: /data/ansible/auto_install_elk_By_Ansible/src

## 部署应用临时存放路径
elk_tmp_dir: /usr/local/src/elk_src_dir

## ELK数据路径
elk_data_dir: /data

## docker-compose编排文件目录
docker_compose_dir: /data/docker-compose

## Installation mode: offline or online
install_mode: offline

### if choise install_mode online
### docker Configuration
registry_mirrors: 'https://gsm39obv.mirror.aliyuncs.com'
insecure_registries: '192.168.2.80:85'

### dns address
DNS1: "8.8.8.8" 
DNS2: "114.114.114.114"

# zookeeper Configuration
zoo_image: zookeeper:3.6.2
zoo_client_port: 2181
zoo_cluster_port: 2888
zoo_leader_port: 3888

# kafka Configuration
kafka_image: wurstmeister/kafka:2.13-2.7.0
kafka_client_port: 9092

# elasticsearch Configuration
elasticsearch_image: elasticsearch:7.11.1
es_client_port: 9200
es_cluster_port: 9300

# logstash Configuration
logstash_image: logstash:7.11.1
logstash_listen_port: 5044

# kibana Configuration
kibana_image: kibana:7.11.1
kibana_server_name: kibana
kibana_client_port: 5601
kibana_vip_port: 5601

# HA Configuration
## 高可用VIP
VIP: 192.168.2.100
## 高可用主机物理网卡名称
nic: ens33

## Nginx Configuration
nginx_image: nginx:1.19.8
